// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxegqmrbjpahnnlarawd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4ZWdxbXJianBhaG5ubGFyYXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTA3NTksImV4cCI6MjA2OTg2Njc1OX0.UEwhgpEthIgFTG0T_KsBBp9GAnEsj5B8BST2xaifh6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});